### PR TITLE
Fix rumble detection

### LINKED ISSUE #750: Can't enable controller rumble on an Xbox controller.
Looking through code i saw mentions about rumble/force feedback but i couldn't find any way to enable it in Duke or Blood. Otherwise controller support is great.

### PR DESCRIPTION
**Pull request by tmyqlfpir**
This PR fixes rumble detection for controllers with EDuke32.

Fixes #750

### CODE REVIEW

**Comment by Hendricks266** [comment]
This change looks fine in itself. I would prefer if it maintained an alternate code path for the older versions of SDL2 before the rumble behavior was changed.

File: source/build/src/sdlayer.cpp [hunk 1]
```diff
@@ -974,10 +974,17 @@ void joyScanDevices()
...
 
-#if SDL_VERSION_ATLEAST(2, 0, 9)
+#if SDL_VERSION_ATLEAST(2, 0, 18)
+                if (EDUKE32_SDL_LINKED_PREREQ(linked, 2, 0, 18))
+                {
+                    if (SDL_GameControllerHasRumble(controller))
+                        joystick.hasRumble = 1;
+                    else DVLOG_F(LOG_INPUT, "Couldn't init controller rumble: %s.", SDL_GetError());
+                }
+#elif SDL_VERSION_ATLEAST(2, 0, 9)
```
Comment (Hendricks266) [inline source/build/src/sdlayer.cpp:984]:
```suggestion
                else
#endif
#if SDL_VERSION_ATLEAST(2, 0, 9)
```

File: source/build/src/sdlayer.cpp [hunk 2]
```diff
@@ -1020,10 +1027,17 @@ void joyScanDevices()
...
 
-#if SDL_VERSION_ATLEAST(2, 0, 9)
+#if SDL_VERSION_ATLEAST(2, 0, 18)
+                if (EDUKE32_SDL_LINKED_PREREQ(linked, 2, 0, 18))
+                {
+                    if (SDL_JoystickHasRumble(joydev))
+                        joystick.hasRumble = 1;
+                    else DVLOG_F(LOG_INPUT, "Couldn't init joystick rumble: %s.", SDL_GetError());
+                }
+#elif SDL_VERSION_ATLEAST(2, 0, 9)
```
Comment (Hendricks266) [inline source/build/src/sdlayer.cpp:1037]:
```suggestion
                else
#endif
#if SDL_VERSION_ATLEAST(2, 0, 9)
```
